# Site settings
title: Scheduler
description: Prototype
baseurl: /sched_ctrl
url: http://dasgringuen.github.io

# Build settings
markdown: kramdown
highlighter: pygments

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
